alias Tree
root = Tree.create_tree()
root = Tree.add_new_node(root, 2)
root = Tree.add_new_node(root, 3)
root = Tree.add_new_node(root, 4)
root = Tree.add_new_node(root, 5)
root = Tree.add_new_node(root, 6)
root = Tree.add_new_node(root, 7)
root = Tree.add_new_node(root, 8)
root = Tree.add_new_node(root, 9)
root = Tree.add_new_node(root, 10)
root = Tree.add_new_node(root, 11)
root = Tree.add_new_node(root, 12)
root = Tree.add_new_node(root, 13)
root = Tree.add_new_node(root, 14)
root = Tree.add_new_node(root, 15)
root = Tree.add_new_node(root, 16)
root = Tree.add_new_node(root, 17)

IO.inspect(root.leftNode.leftNode.leftNode.data)
